stages:
- build
- lint
- test
- staging

before_script:
- export TAG=${CI_COMMIT_SHORT_SHA}
- export BRANCH=${CI_COMMIT_REF_NAME}
- export REGISTRY_HOST=${CI_REGISTRY}
- export REGISTRY_URI="/${CI_PROJECT_PATH}"
- touch stack_car/.env

build:
  stage: build
  script:
    - cd stack_car
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose build web
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose push web
  # only:
  #   refs:
  #     - merge_requests
  #     - main
  tags:
    - local

# lint:
#   stage: go
#   image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
#   variables:
#     PRONTO_GITLAB_API_ENDPOINT: "https://gitlab.com/api/v4"
#   before_script:
#     - export PRONTO_GITLAB_API_PRIVATE_TOKEN=$GITLAB_API_TOKEN
#   script:
#     - cd /home/app/webapp && bundle exec pronto run -f gitlab
#   tags:
#     - docker

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
    - name: mysql:5.7
      alias: db
    - name: bitnami/solr:8
      alias: solr
      entrypoint: ["docker-entrypoint.sh", "solr-precreate", "test"]
    - name: redis:5-alpine
      alias: redis
    - name: samvera/fcrepo4:4.7.5
      alias: fcrepo
    - name: bitnami/zookeeper:3
      alias: zk


  variables:
    MYSQL_DATABASE: ucsc-hyrax
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: ucsc-hyrax
    MYSQL_PASSWORD: password
    MYSQL_HOST: mysql
    DATABASE_ADAPTER: mysql2
    DATABASE_HOST: mysql
    DATABASE_NAME: ucsc-hyrax
    DATABASE_PASSWORD: password
    DATABASE_USER: ucsc-hyrax
    TEST_DB: ucsc-hyrax
  script:
    - cd /app/samvera/hyrax-webapp && bundle exec rake db:create db:schema:load spec
  allow_failure: true
  tags:
    - docker

ucsc.staging:
  stage: staging
  extends:
    - .deploy
  environment:
    name: ucsc.staging
    url: http://ucsc-hyrax-staging.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: ucsc.staging.stop
  # only:
  #   refs:
  #     - n8-staging
  variables:
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE/web
    DEPLOY_TAG: $CI_COMMIT_SHORT_SHA
    HELM_EXPERIMENTAL_OCI: 1
    HELM_RELEASE_NAME: ucsc-hyrax-staging
    KUBE_NAMESPACE: ucsc-hyrax-staging
    HELM_EXTRA_ARGS: >
      --values ops/staging-deploy.yaml
  script:
    - cd stack_car
    - export KUBECONFIG=$KUBECONFIG_R2
    - envsubst < ops/staging-deploy.tmpl.yaml > ops/staging-deploy.yaml
    - ./bin/helm_deploy ucsc-hyrax-staging ucsc-hyrax-staging
  tags:
    - kubernetes
  when: manual

ucsc.staging.stop:
  stage: staging
  extends:
    - .deploy
  environment:
    name: ucsc.staging
    url: http://ucsc-hyrax-staging.$KUBE_INGRESS_BASE_DOMAIN
    action: stop
  when: manual
  allow_failure: true
  script:
    - export KUBECONFIG=$KUBECONFIG_UCSC
    - ./bin/helm_delete ucsc-hyrax-staging ucsc-hyrax-staging
  tags:
    - local

.deploy:
  image: dtzar/helm-kubectl:3.5.3