---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hyrax.cantaloupe.name" . }}
  labels:
    app: {{ template "hyrax.name" . }}
    chart: {{ template "hyrax.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cantaloupe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "hyrax.name" . }}
      release: {{ .Release.Name }}
      component: cantaloupe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "hyrax.name" . }}
        release: {{ .Release.Name }}
        component: cantaloupe
    spec:
      restartPolicy: Always
      {{- if .Values.cantaloupe.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.cantaloupe.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: delegate
          persistentVolumeClaim:
            claimName: {{ template "hyrax.cantaloupe.name" . }}
      containers:
        - name: cantaloupe
          image: {{ .Values.cantaloupe.image.repository }}:{{ .Values.cantaloupe.image.tag }}
          livenessProbe:
            tcpSocket:
              port: 8182
          readinessProbe:
            tcpSocket:
              port: 8182
          volumeMounts:
            - name: delegate
              mountPath: /cantaloupe/delegate
          envFrom:
            - configMapRef:
                name: {{ template "hyrax.cantaloupe-env.name" . }}
