---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hyrax.cantaloupe.name" . }}
  labels:
    app: {{ template "hyrax.name" . }}
    chart: {{ template "hyrax.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: cantaloupe
spec:
  ports:
    - protocol: TCP
      port: 8182
  selector:
    app: {{ template "hyrax.name" . }}
    release: {{ .Release.Name }}
    component: cantaloupe
