apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyrax.fullname" . }}
  labels:
{{ include "hyrax.labels" . | indent 4 }}
type: Opaque
data:
  image_token_secret: {{ randAlphaNum 20 | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  MYSQL_PASSWORD: {{ include "hyrax.mariadb.password" . | b64enc }}
  {{- if .Values.minio.enabled }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey.password | b64enc}}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey.password | b64enc}}
  {{- end }}
  {{- if not .Values.solrExistingSecret }}
  SOLR_ADMIN_PASSWORD: {{ include "hyrax.solr.password" . | b64enc }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc}}
  SIDEKIQ_REDIS_URL: {{ include "hyrax.redis.url" . | b64enc }}
  {{- end }}
