#
# To integrate your app with Google Analytics, uncomment the lines below and add your API key information.
#

analytics:
   app_name: sufia-test
   app_version: 0.1
   privkey_path: /srv/ucsc_sufia/shared/keys/digital-collections-ebde4bdd4cb2.p12
   privkey_secret: notasecret
   client_email: analytics@digital-collections-161623.iam.gserviceaccount.com

