development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://index:8983/solr/hycruz" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://index:8983/solr/hycruz-test" %>
sandbox:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz-staging" %>
staging:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz" %>


