development:
  adapter: solr
  url: http://index:8983/solr/hycruz
test: &test
  adapter: solr
  url: http://index:8983/solr/hycruz-test
staging:
  adapter: solr
  url: http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz-staging
production:
  adapter: solr
  url: http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz


