development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://digitalcollections-ingests.library.ucsc.edu:6379/1

sandbox:
  adapter: redis
  url: redis://digitalcollections-ingests.library.ucsc.edu:6380/1

production:
  adapter: redis
  url: redis://digitalcollections-ingests.library.ucsc.edu:6379/1
