development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV['REDIS_SERVER'] || 'redis://digitalcollections-staging.library.ucsc.edu:6379/1' %>

sandbox:
  adapter: redis
  url: <%= ENV['REDIS_SERVER'] || 'redis://digitalcollections-staging-sandbox.library.ucsc.edu:6379/1' %>

production:
  adapter: redis
  url: <%= ENV['REDIS_SERVER'] || 'redis://digitalcollections-ingests.library.ucsc.edu:6379/1' %>
