default: &default
  user:  <%= ENV["FEDORA_USER"] || 'fedoraAdmin' %>
  password: <%= ENV["FEDORA_PASSWORD"] || 'fedoraAdmin' %>
  url: <%= ENV["FCREPO_URL"] %>
test:
  <<: *default
  base_path: /test
development:
  <<: *default
  base_path: /development
sandbox:
  <<: *default
  base_path: /sandbox
staging:
  <<: *default
  base_path: /prod
production:
  <<: *default
  base_path: /prod
