default: &default
  user:  <%= ENV["FEDORA_USER"] %>
  password: <%= ENV["FEDORA_PASSWORD"] %>
  url: <%= ENV["FEDORA_URL"] %>
test:
  <<: *default
  base_path: /test
development:
  <<: *default
  base_path: /development
