
#-------------------
# Property Settings
#-------------------
# This section defines every metadata property that can be used 
# in the system. Individual work types may override some settings 
# defined here. Predicates for each property should be defined
# here, and cannot be overridden once defined.

fields:

  default:
    definition: "This property has not yet been documented."
    required: false
    multiple: true
    display_group: secondary
    hidden: false
    core: false
    work_title: false
    input: textbox
    data_type: text
    facet_limit: 5
    facet: false
    searchable: false
    stored_in_solr: true
    full_text_searchable: false
    sortable: false

  title:
    definition: "The title of the resource."
    usage_note: "Enter only the primary title of the resource. All other titles should be entered under Alternative Title."
    predicate: "DC:title"
    label: "Title"
    required: true
    primary: true
    display_groups: 
      - primary
      - search_result
    index_itemprop: name
    work_title: true
    searchable: true
    full_text_searchable: true
    OAI: DC:title

  accessionNumber:
    definition: "An archival accession number for the resource."
    label: "Accession Number"
    display_groups: 
      - admin_only
      - editor_primary
    predicate: "DC:identifier"

  titleAlternative:
    definition: "An alternative title for the resource."
    usage_note: "All titles for this work other than the primary title should be listed here"
    label: "Variant Title"
    predicate: "DC:alternative"
    display_groups: 
      - primary
      - search_result
    searchable: true
    full_text_searchable: true
    OAI: DC:alternative

  subseries:
    definition: "A subseries title for the resource."
    usage_note: "This is a descriptive title not necessarily given by the creator that describes one or more related works"
    label: "Sub-Series Title"
    predicate: "BF2:subseriesStatement"
    display_groups: 
      - primary
      - search_result
    searchable: true
    full_text_searchable: true    
    OAI: DC:alternative

  theme:
    definition: "A theme or something theme-like."
    usage_note: ""
    label: "Theme"
    predicate: "opaque:set"
    searchable: true
    full_text_searchable: true

  creator:
    definition: "A person or organization responsible for creating the resource."
    label: Creator
    predicate: "DC:creator"
    vocabularies: 
      - authority: loc
        subauthority: names
      - authority: getty
        subauthority: ulan
      - authority: local
        subauthority: agents
    searchable: true
    full_text_searchable: true
    index_itemprop: creator
    display_groups:
      - primary
      - search_result
    facet: true
    input: textbox_autosuggest
    OAI: DC:creator

  contributor:
    definition: "A person or organization responsible for making contributions to the resource."
    predicate: "DC:contributor"
    label: Contributor
    vocabularies: 
      - authority: loc
        subauthority: names
      - authority: getty
        subauthority: ulan
      - authority: local
        subauthority: agents
    searchable: true
    index_itemprop: contributor
    input: textbox_autosuggest
    OAI: DC:contributor

  originalPublisher:
    predicate: MODS:publisher
    definition: The name of the entity that published, printed, distributed, released, issued, or produced the resource.
    label: Original Publisher
    OAI: MODS:publisher
  
  publisher:
    predicate: "DC:publisher"
    definition: "The organization responsible for publishing the work digitally"
    label: "Digital Publisher & Contact Info"
#    multiple: false
    OAI: DC:publisher
  
  publisherHomepage:
    label: "Publisher Homepage"
    definition: "The URL of the publisher's homepage."
    display_groups: 
      - secondary
      - editor_primary
#    multiple: false
    predicate: FOAF:homepage
  
  resourceType:
    definition: 'General nature or type of the resource (e.g., image, text, etc.). Does not capture aboutness. '
    label: Type
    searchable: true
    predicate: DC:type
    display_groups: 
      - secondary
      - search_result
    vocabulary: 
      - authority: local
        subauthority: dcmi_types
    facet: true
    input: dropdown
    OAI: DC:type
#    multiple: false

  rightsStatement:
    definition: Information about rights held in and over the resource expressed in general terms (i.e. boilerplate statements).
    label: Copyright Statement
    predicate: DC:rights
#    required: 'true'
    OAI: DC:rights
  
  rightsHolder:
    definition: A person or organization owning or managing rights over the resource.
    label: Copyright Holder
    predicate: DC:rightsHolder
    display_groups:
      - secondary
      - editor_primary
    vocabularies: 
      - authority: loc
        subauthority: names
      - authority: local
        subauthority: agents
    input: textbox_autosuggest
    OAI: DC:rights
  
  scale:
    definition: Ratio of the dimensions of a form contained or embodied in a resource to the dimensions of the entity it represents, e.g., for images or cartographic resources.
    predicate: BF2:scale
    label: Scale

  series:
    definition: A related resource in which the described resource is physically or logically included.
    label: Series Title
    predicate: opaque:seriesName
    display_groups: 
      - primary
      - search_result
    facet: true
    searchable: true
    full_text_searchable: true
  
  source:
    definition: A related resource from which the described resource is derived. (Use to record previous publication information, i.e. the place of publication and publisher name for physical resources).
    display_group: admin_only
    label: Source
    predicate: DC:source
  
  staffNote:
    definition: Textual information about the resource. This property is used when no type is specified. 
    label: Staff Note
    display_group: admin_only
    predicate: MODS:note
  
  coordinates:
    definition: Cartographic data that identifies characteristics of the resource, such as coordinates, projection, etc.
    label: Coordinates
    predicate: BF2:cartographicAttributes
  
  subjectName:
    definition: A name of the person that the resource is about.
    label: Subject (People)
    predicate: FOAF:name
    vocabularies:
      - authority: loc
        subauthority: names
      - authority: getty
        subauthority: ulan 
      - authority: local
        subauthority: agents
    facet: true        
    searchable: true
    full_text_searchable: true
    input: textbox_autosuggest
    display_groups:
      - secondary
      - editor_primary
      - search_result
    OAI: DC:subject
  
  subjectPlace:
    definition: Spatial characteristics of the resource.
    label: Subject (Place)
    predicate: DC:spatial
    vocabularies: 
      - authority: geonames
        subauthority:
      - authority: loc
        subauthority: geographicAreas
#      - authority: usgs
#        subauthority: gnis
      - authority: local
        subauthority: places
    facet: true
    searchable: true
    input: textbox_autosuggest
    display_groups:
      - secondary
      - editor_primary
      - search_result
    OAI: DC:subject

  
  subjectTemporal:
    definition: Temporal characteristics of the resource.
    searchable: true
    label: Subject (Time)
    predicate: DC:temporal
    vocabularies: 
      - authority: getty
        subauthority: aat
      - authority: local
        subauthority: time_periods
    facet: true
    searchable: true
    full_text_searchable: true
    input: textbox_autosuggest
    display_groups:
      - secondary
      - editor_primary
      - search_result
    OAI: DC:subject

  
  subjectTopic:
    definition: The topic of the resource.
    label: Subject (Topic)
    predicate: DC:subject
    vocabularies: 
      - authority: loc
        subauthority: subjects
      - authority: local
        subauthority: topics
    facet: true
    searchable: true
    full_text_searchable: true
    index_itemprop: about
    input: textbox_autosuggest
    display_groups:
      - secondary
      - editor_primary
      - search_result
    OAI: DC:subject
  
  dateCreated:
    definition: Date of creation of the original resource.
    encoding: W3CDTF
    label: 'Date Created'
    predicate: DC:date
    data_type: date
    index_itemprop: dateCreated
    input: date
    display_groups:
      - secondary
      - editor_primary
#      - search_result   
#    OAI: DC:date

  dateCreatedDisplay:
    definition: Textual representation of the creation date (temporary fix)
    label: 'Date Created'
    display_groups:
      - secondary
      - editor_primary 
      - search_result
    predicate: MODS:dateCreated
    OAI: DC:date

  dateDigitized:
    definition: Date on which the resource was changed, i.e., digitized.
    encoding: W3CDTF
    label: Date Digitized
    index_itemprop: dateModified
    predicate: DC:modified
#    index_helper_method: human_readable_date
    input: date
    data_type: date
  
  datePublished:
    definition: Date of formal issuance (e.g., publication) of the resource.
    encoding: W3CDTF
    label: 'Date Published'
    index_itemprop: datePublished
    predicate: DC:issued
#    index_helper_method: human_readable_date
    input: date
    data_type: date
  
  description:
    definition: An account of the resource.
    label: Description
    predicate: DC:description
    display_groups: 
      - primary
      - search_result
    index_itemprop: description
#    index_helper_method: "iconify_auto_link"
    searchable: true
    full_text_serachable: true
    OAI: dc:description

  
  relatedResource:
    definition: A link to a relatd resource.
    label: Related Resource
    predicate: DC:relation
  
  physicalFormat:
    definition: The form, and/or physical characteristics of the resource being described. The material or physical carrier of the resource. Does not capture aboutness.
    label: Format
    predicate: DC:medium
    vocabularies: 
      - authority: getty
        subauthority: aat
      - authority: local
        subauthority: formats
    searchable: true
    full_text_searchable: true
    input: textbox_autosuggest
    display_groups:
      - secondary
      - editor_primary
    OAI: DC:format
  
  keyword:
    definition: Keywords (i.e. non-standard terms) assigned to the resource.
    label: Keyword
    predicate: schema:keywords
    index_itemprop: keyword
    display_groups:
      - secondary
      - search_result
    facet: true
    searchable: true
    full_text_searchable: true
  
  language:
    definition: A language of the resource.
    label: Language
    predicate: DC:language
    vocabularies:
      - authority: loc
        subauthority: languages
    index_itemprop: inLanguage
    input: textbox_autosuggest
    display_groups:
      - secondary
      - editor_primary
    OAI: DC:language
  
  license:
    definition: An associated license for the object (i.e. Creative Commons license, software licenses, etc.). Defines use/reuse of resources.
    label: Rights License
    predicate: DC:license
  
  masterFilename:
    definition: "The name of the file (usually attached to this work) that is considered the master digital file to represent the work."
    predicate: EBUCore:filename
    searchable: true
    full_text_searchable: true
    label: Master File Name
    display_groups: 
      - secondary
      - editor_primary
    OAI: DC:identifier
  
  physicalDescription:
    definition: Description or statement indicating the extent, size, or duration of the original, physical resource for digitized content.
    label: Physical Description
    predicate: DC:extent
  
  accessRights:
    definition: Information about who can access the resource or an indication of its security status.
    display_groups:
      - secondary
      - editor_primary
    label: Access Rights
    predicate: DC:accessRights
    OAI: DC:rights
    
  itemCallNumber:
    definition: Classification number in any scheme.
    label: Item Call Number
    predicate: BF2:classification
    display_groups:
      - secondary
      - editor_primary
    OAI: DC:identifier

  collectionCallNumber:
    definition: The identifier for the collection to which the resource belongs.
    label: Collection Call Number
    predicate: schema:identifier
    display_groups:
      - secondary
      - editor_primary
    OAI: DC:source

  donorProvenance:
    definition: "A statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation."
    label: Donor/Provenance
    predicate: DC:provenance

  genre:
    definition: "A genre term designates the style or technique of the intellectual content of textual materials or, for graphic materials, aspects such as vantage point, intended purpose, characteristics of the creator, publication status, or method  of representation. Does not capture aboutness. Ex. lectures; underground dance music."
    label: Genre
    vocabulary:
      - authority: local
        subauthority: genres
    predicate:  MODS:subjectGenre
    input: dropdown

  boxFolder:
    definition: "A call number, shelf mark or similar label of an item. Format \"Box X, Folder Y\"."
    label: "Call Number (Box/Folder)"
    usage note: "Format: \"Box X, Folder Y\"."
    predicate:  purlOnt:holding#label

#-------------------
# RDF Namespaces
#-------------------
# Here we can define additional namespaces for rdf predicates.
# The most common namespaces are predefined by the system, but
# this allows us to define more.

namespaces:
  edm: "http://www.europeana.eu/schemas/edm/"
  opaque: "http://opaquenamespace.org/ns/"
  schema: "http://schema.org/"
  purlOnt: "http://purl.org/ontology/"
