#-------------------
# Other Schema Files
#-------------------
# This section specifies other configuration files that contain
# metadata information. Each other metadata file may contain 
# any information that would be valid in this file. Schema information
# from all files is merged together.
# When possible, information from all files is combined. For example, 
# if a property is defined in one file, it cannot be un-defined in 
# another file, though more options can be added.
# Some options associated with properties can be defined in one file
# and overwritten by another. Options like this include 'required'
# and 'multiple'. 
# Other options must be defined only once per property
# and cannot be overwritten. These include "predicate" and "definition". 


# NO OTHER SCHEMA FILES USED 


#-------------------
# Property Settings
#-------------------
# This section defines every metadata property that can be used 
# in the system. Individual work types may override some settings 
# defined here. Predicates for each property should be defined
# here, and cannot be overridden once defined.

properties:

  default:
    definition: "This property has not yet been documented."
    required: false
    multiple: true
    primary: false
    hidden: false
    display_area: more
    core: false
    work_title: false
    input: scalar
    facet_limit: 5
    index_as: stored_searchable
    search_field: false
    sort_field: false
    index_field: false
    input_as: text
    search_result_display: true
#    class_name: Ucsc::ControlledResource

  title:
    definition: "The title of the resource."
    usage_note: "Enter only the primary title of the resource. All other titles should be entered under Alternative Title."
    predicate: "DC:title"
    label: "Title"
    required: true
#    multiple: false
    primary: true
    core: true
    display_area: work_title
    work_title: tre
    index_itemprop: name
    index_if: false
    index_field: true
    search_field: true
    OAI: DC:title

  accessionNumber:
    definition: "An archival accession number for the resource."
    DC mapping: "DC:identifier"
    label: "Accession Number"
    display_area: staff
    core: true
    predicate: "DC:identifier"
    primary: true
#    multiple: false

  titleAlternative:
    definition: "An alternative title for the resource."
    usage_note: "All titles for this work other than the primary title should be listed here"
    label: "Variant Title"
    predicate: "DC:alternative"
    search_field: true
    OAI: DC:alternative

  subSeries:
    definition: "A subseries title for the resource."
    usage_note: "This is a descriptive title not necessarily given by the creator"
    label: "Sub-Series Title"
    predicate: "DC:subseriesStatement"
    search_field: true
    OAI: DC:alternative

  theme:
    definition: "A theme or something theme-like."
    usage_note: ""
    label: "Theme"
    predicate: "opaque:set"
    search_field: true

  creator:
    definition: "A person or organization responsible for creating the resource."
    predicate: "DC:creator"
    range: "Agent"
    vocabularies: 
      - authority: loc
        subauthority: names
      - authority: getty
        subauthority: ulan
      - authority: local
        subauthority: agents
    primary: true
#    required: true
    facet: true
    index_itemprop: creator
    search_field: true
    input: multi_controlled_vocabulary
    core: true
    OAI: DC:creator

  contributor:
    definition: "A person or organization responsible for making contributions to the resource."
    predicate: "DC:contributor"
    range: "Agent"
    vocabularies: 
      - authority: loc
        subauthority: names
      - authority: getty
        subauthority: ulan
      - authority: local
        subauthority: agents
    facet: true
    index_itemprop: contributor
    search_field: true
    core: true
    display_area: more
    input: autosuggest
    OAI: DC:contributor

  originalPublisher:
    predicate: MODS:publisher
    definition: The name of the entity that published, printed, distributed, released, issued, or produced the resource.
    label: Original Publisher
    OAI: MODS:publisher
  
  publisher:
    predicate: "DC:publisher"
    label: "Digital Publicher & Contact Info"
#    multiple: false
    core: true
    OAI: DC:publisher
  
  publisherHomepage:
    definition: "The URL of the publisher's homepage."
#    multiple: false
    predicate: FOAF:homepage
    core: true
  
  resourceType:
    definition: 'General nature or type of the resource (e.g., image, text, etc.). Does not capture aboutness. '
    label: Type
    search_field: true
    predicate: DC:type
    required: true
    vocabulary: 
      authority: local
      subauthority: dcmi_types
    facet: true
    input: dropdown
    OAI: DC:type
#    multiple: false
#    search_result_display: true
   
  
  rightsStatement:
    definition: Information about rights held in and over the resource expressed in general terms (i.e. boilerplate statements).
    DC mapping: dc:rights
    label: Copyright Statement
    predicate: DC:rights
    required: 'true'
    core: true
    OAI: DC:rights
  
  rightsHolder:
    definition: A person or organization owning or managing rights over the resource.
    DC mapping: dc:rightsHolder
    label: Copyright Holder
    predicate: DC:rightsHolder
    vocabularies: 
      - authority: loc
        subauthority: names
      - authority: local
        subauthority: agents
    input: autosuggest
    core: true
    OAI: DC:rights
  
  scale:
    definition: Ratio of the dimensions of a form contained or embodied in a resource to the dimensions of the entity it represents, e.g., for images or cartographic resources.
    predicate: BF2:scale

  series:
    definition: A related resource in which the described resource is physically or logically included.
    label: Series Title
    predicate: opaque:seriesName
    search_field: true
  
  source:
    definition: A related resource from which the described resource is derived. (Use to record previous publication information, i.e. the place of publication and publisher name for physical resources).
    display_area: staff
    predicate: DC:source
    search_field: true
  
  staffNote:
    definition: Textual information about the resource. This property is used when no type is specified. 
    label: Staff Note
    display_area: staff
    predicate: MODS:note
  
  coordinates:
    definition: Cartographic data that identifies characteristics of the resource, such as coordinates, projection, etc.
    DC mapping: dc:relation
    label: Coordinates
    predicate: BF2:cartographicAttributes
  
  subjectName:
    definition: A name of the person that the resource is about.
    DC mapping: dc:subject
    label: Subject (People)
    predicate: FOAF:name
    vocabularies:
      - authority: loc
        subauthority: names
      - authority: getty
        subauthority: ulan 
      - authority: local
        subauthority: agents        
    facet: true
    input: autosuggest
    core: true
    OAI: DC:subject
#    search_result_display: true
  
  subjectPlace:
    definition: Spatial characteristics of the resource.
    DC mapping: dc:subject
    label: Subject (Place)
    predicate: DC:spatial
    vocabularies: 
      - authority: loc
        subauthority: geographic_areas
      - authority: usgs
        subauthority: gnis
      - authority: local
        subauthority: places
    facet: true
    search_field: true
    input: autosuggest
    core: true
    OAI: DC:subject
#    search_result_display: true
  
  subjectTemporal:
    definition: Temporal characteristics of the resource.
    DC mapping: dc:subject
    search_field: true
    label: Subject (Time)
    predicate: DC:temporal
    vocabularies: 
      - authority: getty
        subauthority: aat
      - authority: local
        subauthority: time_periods
    facet: true
    input: autosuggest
    core: true
    OAI: DC:subject
#    search_result_display: true
  
  subjectTopic:
    definition: The topic of the resource.
    DC mapping: dc:subject
    label: Subject (Topic)
    predicate: DC:subject
    vocabularies: 
      - authority: loc
        subauthority: subjects
      - authority: local
        subauthority: topics
    index_itemprop: about
    facet: true
    search_field: true
    input: autosuggest
    core: true
    OAI: DC:subject
#    search_result_display: true
  
  dateCreated:
    definition: Date of creation of the original resource.
    encoding: W3CDTF
    label: 'Date Created'
    predicate: DC:date
#    index_helper_method: human_readable_date
    index_itemprop: dateCreated
    input: date
    core: true    
    OAI: DC:date
#    search_result_display: true

  dateCreatedDisplay:
    definition: Textual representation of the creation date (temporary fix)
    label: 'Date Created'
    predicate: MODS:dateCreated

  dateDigitized:
    definition: Date on which the resourc was changed, i.e., digitized.
    encoding: W3CDTF
    label: Date Digitized
    predicate: DC:modified
#    index_helper_method: human_readable_date
    index_itemprop: dateModified
    input: date
  
  datePublished:
    definition: Date of formal issuance (e.g., publication) of the resource.
    encoding: W3CDTF
    label: 'Date Published'
    predicate: DC:issued
#    index_helper_method: human_readable_date
    index_itemprop: datePublished
    input: date
  
  description:
    definition: An account of the resource.
    label: Description
    predicate: DC:description
    index_field: true
    index_itemprop: "description"
    index_helper_method: "iconify_auto_link"
    search_field: true
    OAI: dc:description
#    search_result_display: true
  
  physicalFormat:
    definition: The form, and/or physical characteristics of the resource being described. The material or physical carrier of the resource. Does not capture aboutness.
    DC mapping: dc:medium
    label: Format
    predicate: DC:medium
    vocabularies: 
      - authority: getty
        subauthority: aat
      - authority: local
        subauthority: formats
    facet: true
    input: autosuggest
    core: true
    OAI: DC:format
  
  keyword:
    definition: Keywords (i.e. non-standard terms) assigned to the resource.
    label: Keyword
    predicate: schema:keywords
    facet: true
    index_itemprop: keywords
    search_field: true
#    search_result_display: true
  
  language:
    definition: A language of the resource.
    DC mapping: dc:language
    label: Language
    predicate: DC:language
    vocabularies:
      - authority: loc
      - subauthority: languages
    facet: true
    itemprop: inLanguage
    input: dropdown
    core: true
    OAI: DC:language
  
  license:
    definition: An associated license for the object (i.e. Creative Commons license, software licenses, etc.). Defines use/reuse of resources.
    label: Rights License
    predicate: DC:license
  
  masterFilename:
    definition: "The name of the file (usually attached to this work) that is considered the master digital file to represent the work."
    predicate: EBUCore:filename
    core: true
    label: Master File Name
    display_area: staff
  
  physicalDescription:
    definition: Description or statement indicating the extent, size, or duration of the original, physical resource for digitized content.
    label: Physical Description
    predicate: DC:extent
  
  accessRights:
    definition: Information about who can access the resource or an indication of its security status.
    core: true
    label: Access Rights
    predicate: DC:accessRights
    OAI: dc:rights
    
#  collection:
#    definition: A related resource in which the described resource is physi#cally or logically included.
#    DC mapping: dc:relation
#    label: Collection Title
#    predicate: DC:isPartOf
#    facet: true
  
  itemCallNumber:
    definition: Classification number in any scheme.
    DC mapping: dc:source
    label: Call Number
    predicate: BF2:classification
    core: true
    display_area: brief

  collectionCallNumber:
    definition: The identifier for the collection to which the resource belongs.
    DC mapping: dc:source
    label: Call Number
    predicate: schema:identifier
    core: true
    display_area: brief
    OAI: DC:identifier

  donorProvenance:
    definition: "A statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation."
    DC mapping: DC:provenance
    label: Donor/Provenance
    predicate: DC:provenance

  genre:
    definition: "A genre term designates the style or technique of the intellectual content of textual materials or, for graphic materials, aspects such as vantage point, intended purpose, characteristics of the creator, publication status, or method  of representation. Does not capture aboutness. Ex. lectures; underground dance music."
    vocabulary:
      - authority: loc
      - subauthority: languages
    predicate:  MODS:subjectGenre

  boxFolder:
    definition: "A call number, shelf mark or similar label of an item. Format \"Box X, Folder Y\"."
    label: "Call Number"
    usage note: "Format: \"Box X, Folder Y\"."
    DC mapping: DC:identifier
    predicate:  purlOnt:holding#label

#
#-------------------
# Work Type Settings
#-------------------
# Here we define metadata settings based on work type.
# This section specifies which properties (defined above)
# may be applied to each work type, and may specify display
# settings such as "required" or "hidden".
# 
# In the future, this may be extended to actually define 
# the work types for the application here.


work_types:
  work:
    properties:
      title:
      titleAlternative:
        primary: true
      subseries:
        primary: true
      creator:
      contributor:
      publisher:
      publisherHomepage:
        primary: true
      description:
        primary: true
      language:
      resourceType:
      rightsHolder:
      rightsStatement:
      scale:
      source:
      staffNote:
      accessRights:
      license:
      collection:
      series:
      coordinates:
      dateCreated:
      dateCreatedFake:
      datePublished:
      dateDigitized:
      subjectTopic:
      subjectName:
      subjectPlace:
      subjectTemporal:
      genre:
      physicalFormat:
      masterFilename:
      originalPublisher:
      physicalDescription:
      keyword:
      accessionNumber:
      collectionCallNumber:
      donorProvenance:
      boxFolder:
      theme:
      itemCallNumber:
  collection:
    properties:
      title:
      titleAlternative:
        primary: true
      creator:
      contributor:
      publisher:
      publisherHomepage:
        primary: true
      description:
        primary: true
      language:
      resourceType:
      rightsHolder:
      rightsStatement:
      accessRights:
      license:
      dateCreated:
      datePublished:
      dateModified:
      subjectTopic:
      subjectName:
      subjectPlace:
      subjectTemporal:
      keyword:
      collectionCallNumber:
      donorProvenance:
  lecture:
    properties:
      title:
        inherit: prepend
      description:
        primary: true
      creator:
      license:
        inherit: true
      keyword:
        inherit: true
      dateCreated:
  course:
    properties:
      title:
      description:
        primary: true
      creator:
        primary: true
      license:
      keyword:
      dateCreated:
  gdao_work:
    properties:
      title:
      description:
      dateCreated:


#-------------------
# RDF Namespaces
#-------------------
# Here we can define additional namespaces for rdf predicates.
# The most common namespaces are predefined by the system, but
# this allows us to define more.

namespaces:
  edm: "http://www.europeana.eu/schemas/edm/"
  opaque: "http://opaquenamespace.org/ns/"
  schema: "http://schema.org/"
  purlOnt: "http://purl.org/ontology/"