
# You can use any metadata element defined in metadata.yml 
# or any valid method of a SolrDocument that requires no arguments
default:
  title:
    - title
  alternative:
    - titleAlternative
    - subseries
  creator:
    - creator
  contributor:
    - contributor
  publisher:
    - originalPublisher
  type:
    - resourceType
  rights:
    - rightsHolder
  subject:
    - subjectName
    - subjectPlace
    - subjectTemporal
    - subjectTopic
  date:
    - dateCreated
    - dateCreatedDisplay
  description:
    - description
  format:
    - physicalformat
  language:
    - language   
  identifier:
    - masterFilename
    - itemCallNumber
  source:
    - member_of_collections_ssim
    - collectionCallNumber   
DC:
  parent_schema: default
  identifier:
    - masterFilename
    - itemCallNumber
    - display_image_url
DPLA:
  parent_schema: default
  object:
    - display_image_url
  isShownAt:
    - permalink