default:
development:
  host: <%= ENV['REDIS_HOST'] || "redis" %>
  port: 6379
test:  
  host: <%= ENV['REDIS_HOST'] || "redis" %>
  port: 6379
production:
  host: <%= ENV['REDIS_HOST'] || "digitalcollections-deploy.library.ucsc.edu" %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  port: 6379
staging:
  host: <%= ENV['REDIS_HOST'] || "digitalcollections-deploy.library.ucsc.edu" %>
  port: 6379
sandbox:
  host: <%= ENV['REDIS_HOST'] || "digitalcollections-deploy.library.ucsc.edu" %>
  port: 6380
