default:
development:
  host: redis
  port: 6379
test:  
  host: redis
  port: 6379
production:
  host: digitalcollections-ingests.library.ucsc.edu
staging:
  host: digitalcollections-ingests.library.ucsc.edu
  port: 6380
