development:
  archivist:
    - archivist1@example.com
    - ethenry@ucsc.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
staging:
  archivist:
    - archivist1@example.com
    - ethenry@ucsc.edu
sandbox:
  archivist:
    - archivist1@example.com
    - ethenry@ucsc.edu
production:
  archivist:
    - archivist1@example.com
    - ethenry@ucsc.edu

