# This is a sample config file that points to a solr server for each environment
development:
#  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra_development
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
test:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-test
production:
  url: http://sufia-dev.library.ucsc.edu:8983/solr/hydra
