# This config file points to a solr server for each environment
development:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
test:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
staging:
  url: http://digitalcollections-staging.library.ucsc.edu:8983/solr/hydra
production:
  url: http://digitalcollections.library.ucsc.edu:8983/solr/hydra
