development:
  url: <%= ENV['SOLR_URL'] || "http://index:8983/solr/hycruz" %>
test:
  url: <%= ENV['SOLR_URL'] || "http://index:8983/solr/hycruz-test" %>
sandbox:
  url: <%= ENV['SOLR_URL'] || "http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz-staging" %>
staging:
  url: <%= ENV['SOLR_URL'] || "http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz" %>
production:
  url: <%= ENV['SOLR_URL'] || "http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz" %>

