# This config file points to a solr server for each environment
development:
  url: http://index:8983/solr/hycruz
test:
  url: http://index:8983/solr/hycruz-test
staging:
  url: http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz-staging
production:
  url: http://digitalcollections-index.library.ucsc.edu:8983/solr/hycruz

