version: "3"

x-app: &app
  image: registry.gitlab.com/notch8/ucsc-library-digital-collections/web:${TAG:-latest}
  build:
    context: ..
    dockerfile: ./stack_car/Dockerfile
    target: hyku-base
    args:
      - EXTRA_APK_PACKAGES=less vim bash openjdk11-jre ffmpeg rsync
  # command: sh -l -c "bundle && bundle exec puma -v -b tcp://0.0.0.0:3000"
  # image: registry.gitlab.com/notch8/britishlibrary:${TAG:-latest}
  env_file:
    - .env
  # NOTE: all common env variables moved to .env
  volumes:
    - uploads:/app/samvera/hyrax-webapp/public/uploads
    - assets:/app/samvera/hyrax-webapp/public/assets
    - cache:/app/samvera/hyrax-webapp/tmp/cache
    - .:/app/samvera/hyrax-webapp
  networks:
    internal:

services:
  web:
    <<: *app
    container_name: hycruz
    volumes:
     - "../dams_derivatives:/dams_derivatives:z"
     - "../hyrax:/srv/hycruz:z"
     - "gems:/srv/bundle:Z"
     - "../dams_ingest:/dams_ingest"
     - "../scooby_snacks:/srv/scooby_snacks"
     - "../samvera_hls:/srv/samvera_hls"
     - "../bulk_ops:/srv/bulk_ops"
     - "./config/database.yml:/srv/hycruz/config/database.yml"
     - "./config/secrets.yml:/srv/hycruz/config/secrets.yml"
     - "./config/fedora.yml:/srv/hycruz/config/fedora.yml"
     - "./config/github.yml:/srv/hycruz/config/github.yml"
     - "./example_media:/srv/hycruz/public/example_media"
    environment: 
      - IIIF_SERVER_URL=http://localhost:8182/iiif/2/
    depends_on:
      - "db"
      - "repo"
      - "index"
      - "redis"
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.development
    networks:
      front-tier:
        aliases: 
          - hycruz
          - hyrax
          - app
          - application
      back-tier:
        aliases:
          - hycruz
          - hyrax
          - app
          - application
  worker:
    <<: *app
    image: registry.gitlab.com/notch8/ucsc-library-digital-collections/worker:${TAG:-latest}
    container_name: worker
    volumes:
     - "../dams_derivatives:/dams_derivatives:z"
     - "../hyrax:/srv/hycruz:z"
     - "gems2:/srv/bundle:Z"
     - "../dams_ingest:/dams_ingest"
     - "../scooby_snacks:/srv/scooby_snacks"
     - "../samvera_hls:/srv/samvera_hls"
     - "../bulk_ops:/srv/bulk_ops"
     - "../fits:/srv/fits"
     - "./config/database.yml:/srv/hycruz/config/database.yml"
     - "./config/secrets.yml:/srv/hycruz/config/secrets.yml"
     - "./config/fedora.yml:/srv/hycruz/config/fedora.yml"
     - "./config/github.yml:/srv/hycruz/config/github.yml"
     - "./example_media:/srv/hycruz/public/example_media"
     - "./kakadu:/usr/share/kakadu"
    env_file:
      - .env
      - .env.development
    depends_on:
      - "db"
      - "repo"
      - "index"
      - "redis"
    networks:
      back-tier:
        aliases:
          - sidekiq
          - worker_1
  repo:
    image: registry.gitlab.com/notch8/ucsc-docker/repo:latest
    build:  
      context: .
      dockerfile: repo-dockerfile
    container_name: fcrepo
    volumes:
      - "repository-data:/opt/fcrepo/data:Z"
    ports:
      - "8080:8080"
    networks:
      back-tier:
        aliases:
          - repository
          - fedora
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    env_file:
      - .env
      - .env.development
    restart: always
    volumes:
      - "database-data:/var/lib/mysql:Z"
    networks:
      back-tier:
        aliases:
          - database
          - mysql
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      back-tier:
        aliases:
          - queue
  index:
    image: solr:7.7
    container_name: solr
    command: "bash -c 'precreate-core hycruz /opt/config && precreate-core hycruz-test /opt/config && solr-foreground'"
    ports: 
      - "8983:8983"
    volumes:
      - "./solr_conf:/opt/config:Z"
      - "index-data:/opt/solr/server/solr:Z"
    networks:
      back-tier:
        aliases:
          - solr
  images:
    image: registry.gitlab.com/notch8/ucsc-library-digital-collections/images:${TAG:-latest}
    build:  
      context: ..
      dockerfile: ./stack_car/cantaloupe/cantaloupe-dockerfile
    container_name: cantaloupe
    depends_on:
      - "repo"
    ports:
      - "8182:8182"
      - "8183:8183"
    volumes:
      - "../dams_derivatives:/dams_derivatives:z"
      - "cantaloupe-log:/srv/cantaloupe-log:Z"
      - "cantaloupe-cache:/srv/cantaloupe-cache:Z"
      - "./kakadu:/usr/share/kakadu"
    networks:
      front-tier:
        aliases: 
          - images
          - cantaloupe
          - hycruz-images
      back-tier:
        aliases:
          - images
          - cantaloupe
          - hycruz-images
volumes:
  database-data:
  gems:
  gems2:
  cantaloupe-log:
  cantaloupe-cache:
  index-data:
  redis-data:
    driver: local
  repository-data:
networks:
  front-tier:
  back-tier:
